### ISSUE TITLE
Error prototypes method getJREDirName

### ISSUE THREAD

**Issue by ago75** [crotwell/gradle-macappbundle#51]
thanks for the job, i'm performing the task with android studio and jdk 1.8+ and i have this problem:

FAILURE: Build failed with an exception.

* What went wrong:
Ambiguous method overloading for method java.io.File#<init>.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
	[class java.lang.String]
	[class java.net.URI]

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method java.io.File#<init>.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
	[class java.lang.String]
	[class java.net.URI]
	at com.github.cr0.gradle.macAppBundle.MacAppBundlePluginExtension.getJREDirName(MacAppBundlePluginExtension.groovy:166)
	at com.github.cr0.gradle.macAppBundle.MacAppBundlePluginExtension$getJREDirName$0.call(Unknown Source)
	at com.github.cr0.gradle.macAppBundle.MacAppBundlePlugin$_createBundleJRETask_closure22.doCall(MacAppBundlePlugin.groovy:166)
	at org.gradle.api.internal.file.FileOrUriNotationConverter.convert(FileOrUriNotationConverter.java:85)
	at org.gradle.internal.typeconversion.NotationConverterToNotationParserAdapter.parseNotation(NotationConverterToNotationParserAdapter.java:30)
	at org.gradle.internal.typeconversion.ErrorHandlingNotationParser.parseNotation(ErrorHandlingNotationParser.java:47)
	at org.gradle.api.internal.file.AbstractFileResolver.convertObjectToFile(AbstractFileResolver.java:125)
	at org.gradle.api.internal.file.AbstractBaseDirFileResolver.doResolve(AbstractBaseDirFileResolver.java:69)
	at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:86)
	at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:68)
	at org.gradle.api.internal.file.copy.DestinationRootCopySpec.getDestinationDir(DestinationRootCopySpec.java:48)
	at org.gradle.api.internal.file.copy.DestinationRootCopySpec_Decorated.getDestinationDir(Unknown Source)
	at org.gradle.api.tasks.Sync.getDestinationDir(Sync.java:100)
	at org.gradle.api.tasks.Sync_Decorated.getDestinationDir(Unknown Source)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.TaskPropertyInfo$4.create(TaskPropertyInfo.java:99)
	at org.gradle.util.SingleMessageLogger.whileDisabled(SingleMessageLogger.java:217)
	at org.gradle.api.internal.project.taskfactory.TaskPropertyInfo.getValue(TaskPropertyInfo.java:97)
	at org.gradle.api.internal.project.taskfactory.TaskClassValidator$FutureValue.call(TaskClassValidator.java:65)
	at org.gradle.util.GUtil.uncheckedCall(GUtil.java:432)
	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResolve(DefaultFileCollectionResolveContext.java:125)
	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolveAsFileCollections(DefaultFileCollectionResolveContext.java:94)
	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext$FileCollectionConverter.convertInto(DefaultFileCollectionResolveContext.java:161)
	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResolve(DefaultFileCollectionResolveContext.java:111)
	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolveAsFileCollections(DefaultFileCollectionResolveContext.java:94)
	at org.gradle.api.internal.file.CompositeFileCollection.getSourceCollections(CompositeFileCollection.java:172)
	at org.gradle.api.internal.file.CompositeFileCollection.getFiles(CompositeFileCollection.java:55)
	at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:68)
	at com.google.common.collect.Iterables$8.iterator(Iterables.java:713)
	at com.google.common.collect.Sets.newHashSet(Sets.java:219)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.canonicalizedPaths(DefaultTaskExecutionPlan.java:709)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.getOutputPaths(DefaultTaskExecutionPlan.java:785)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.recordTaskStarted(DefaultTaskExecutionPlan.java:815)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.access$2700(DefaultTaskExecutionPlan.java:91)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan$9.transform(DefaultTaskExecutionPlan.java:601)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan$9.transform(DefaultTaskExecutionPlan.java:590)
	at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:45)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.selectNextTask(DefaultTaskExecutionPlan.java:590)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.access$2300(DefaultTaskExecutionPlan.java:91)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan$8.transform(DefaultTaskExecutionPlan.java:564)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan$8.transform(DefaultTaskExecutionPlan.java:545)
	at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:45)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:545)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

**Comment by crotwell** [comment]
What version of macAppBundle are you using?

Can you share your build.gradle, or at least the macAppBundle section?

Is this on a mac? What version of OSX?

Thanks for reporting this.

**Comment by ago75** [comment]
tool: Android Studio 3.0
gradle version: gradle-4.1
gradle plugin: 'com.android.tools.build:gradle:3.0.0'
os: macOS Sierra 10.12.6


plugins {
    id 'java-library'
    id 'maven'
	id "edu.sc.seis.launch4j" version "2.4.2"
    id "edu.sc.seis.macAppBundle" version "2.1.9"
}

macAppBundle {
    appName = "MapsCreator"
    icon = "src/main/resources/ic_launcher.icns"
    version = "1.0"
    mainClassName = "it.jago.navigator.MapsCreator"
    bundleJRE = false
    bundleExecutable = "MapsCreator"
    bundleIdentifier = "it.jago.navigator.MapsCreator"
    bundleExtras.put("NSHighResolutionCapable", "true")
    //javaProperties.put("file.encoding", "utf-8")
    javaExtras.put("X","mx8192M")
    //javaXProperties.add("startOnFirstThread")
    dmgName = "MapsCreator 0.1-alpha1"
}


tasks.withType(JavaCompile) {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}


another question : is correct javaExtras.put("X","mx8192M") for jvm option?

thank!

**Comment by crotwell** [comment]
OK. I have not been able to reproduce this here, and the next version, 2.2.0, will be source/target java version of 1.8, so closing as hopefully this is resolved. Let me know if not.
